// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wcmkhtylkmxerkqmkarm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndjbWtodHlsa214ZXJrcW1rYXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzY1NjksImV4cCI6MjA1NzcxMjU2OX0.QoKbrxY3AIGzWaWPsenpabtQex7zzB_pGVVFyGMnWbI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);